version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
    versioning-strategy: increase
    target-branch: "main"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "fix"
      prefix-development: "build"
    groups:
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
      time: "03:00"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
      day: "sunday"
      time: "03:00"
