repos:
- hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
- hooks:
  - files: \.[jt]sx?$
    id: eslint
    types:
    - file
  repo: https://github.com/pre-commit/mirrors-eslint
  rev: v9.19.0
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - pre-push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v4.1.1
